version: '3.8'  # 新しいバージョンに変更

services:
  mysql:
    image: mysql:8.0.27
    platform: linux/x86_64
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}  # 環境変数からパスワードを取得
      MYSQL_DATABASE: kobe
      MYSQL_USER: root
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}  # 環境変数からパスワードを取得
      TZ: 'Asia/Tokyo'
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_USER: root  # ユーザーを指定
      PMA_PASSWORD: ${MYSQL_PASSWORD:-password}  # 環境変数からパスワードを取得
    ports:
      - "8090:80"

  python:
    build: ./python
    volumes:
      - ./python:/usr/src/app
    depends_on:
      - mysql

volumes:
  db-data:
